// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: query.proto

package query

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// QueryProcessorClient is the client API for QueryProcessor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryProcessorClient interface {
	QueryData(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
}

type queryProcessorClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryProcessorClient(cc grpc.ClientConnInterface) QueryProcessorClient {
	return &queryProcessorClient{cc}
}

func (c *queryProcessorClient) QueryData(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, "/api.QueryProcessor/QueryData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryProcessorServer is the server API for QueryProcessor service.
// All implementations must embed UnimplementedQueryProcessorServer
// for forward compatibility
type QueryProcessorServer interface {
	QueryData(context.Context, *QueryRequest) (*QueryResponse, error)
	mustEmbedUnimplementedQueryProcessorServer()
}

// UnimplementedQueryProcessorServer must be embedded to have forward compatible implementations.
type UnimplementedQueryProcessorServer struct {
}

func (UnimplementedQueryProcessorServer) QueryData(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryData not implemented")
}
func (UnimplementedQueryProcessorServer) mustEmbedUnimplementedQueryProcessorServer() {}

// UnsafeQueryProcessorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryProcessorServer will
// result in compilation errors.
type UnsafeQueryProcessorServer interface {
	mustEmbedUnimplementedQueryProcessorServer()
}

func RegisterQueryProcessorServer(s grpc.ServiceRegistrar, srv QueryProcessorServer) {
	s.RegisterService(&QueryProcessor_ServiceDesc, srv)
}

func _QueryProcessor_QueryData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryProcessorServer).QueryData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.QueryProcessor/QueryData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryProcessorServer).QueryData(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QueryProcessor_ServiceDesc is the grpc.ServiceDesc for QueryProcessor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QueryProcessor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.QueryProcessor",
	HandlerType: (*QueryProcessorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryData",
			Handler:    _QueryProcessor_QueryData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "query.proto",
}
