// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: api.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DataReceiverClient is the client API for DataReceiver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataReceiverClient interface {
	SubmitRawData(ctx context.Context, in *Packet, opts ...grpc.CallOption) (*SubmitResponse, error)
}

type dataReceiverClient struct {
	cc grpc.ClientConnInterface
}

func NewDataReceiverClient(cc grpc.ClientConnInterface) DataReceiverClient {
	return &dataReceiverClient{cc}
}

func (c *dataReceiverClient) SubmitRawData(ctx context.Context, in *Packet, opts ...grpc.CallOption) (*SubmitResponse, error) {
	out := new(SubmitResponse)
	err := c.cc.Invoke(ctx, "/api.DataReceiver/SubmitRawData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataReceiverServer is the server API for DataReceiver service.
// All implementations must embed UnimplementedDataReceiverServer
// for forward compatibility
type DataReceiverServer interface {
	SubmitRawData(context.Context, *Packet) (*SubmitResponse, error)
	mustEmbedUnimplementedDataReceiverServer()
}

// UnimplementedDataReceiverServer must be embedded to have forward compatible implementations.
type UnimplementedDataReceiverServer struct {
}

func (UnimplementedDataReceiverServer) SubmitRawData(context.Context, *Packet) (*SubmitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitRawData not implemented")
}
func (UnimplementedDataReceiverServer) mustEmbedUnimplementedDataReceiverServer() {}

// UnsafeDataReceiverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataReceiverServer will
// result in compilation errors.
type UnsafeDataReceiverServer interface {
	mustEmbedUnimplementedDataReceiverServer()
}

func RegisterDataReceiverServer(s grpc.ServiceRegistrar, srv DataReceiverServer) {
	s.RegisterService(&DataReceiver_ServiceDesc, srv)
}

func _DataReceiver_SubmitRawData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Packet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataReceiverServer).SubmitRawData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.DataReceiver/SubmitRawData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataReceiverServer).SubmitRawData(ctx, req.(*Packet))
	}
	return interceptor(ctx, in, info, handler)
}

// DataReceiver_ServiceDesc is the grpc.ServiceDesc for DataReceiver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataReceiver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.DataReceiver",
	HandlerType: (*DataReceiverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitRawData",
			Handler:    _DataReceiver_SubmitRawData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
